import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RegisterPage from './Register/page';
import NavigationBar from "../app/components/NavigationBar";
import Footer from "../app/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex flex-column min-vh-100`}>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
